### ISSUE TITLE
changing the material and texture of the hands

### ISSUE THREAD

**Issue by addy1997** [c-frame/aframe-super-hands-component#237]
Hi @wmurphyrd,

Is it possible to change the default white colour of the hands to a more human-like skin colour? Also, it is possible to give a similar texture to the hands. My application trains dentists for implant placement and therefore I am using the superhands component to allow the dentists to rotate, grab, stretch, and manipulate the entities.

![image](https://github.com/c-frame/aframe-super-hands-component/assets/29406906/e75a6c88-ab42-47e4-a49d-9a8881c6f11b)

**Comment by wmurphyrd** [comment]
Hi that sounds like a very good use case. Super-hands doesn't provide the graphical representation of the hands or controllers. Maybe you're using hand-controls? https://aframe.io/docs/1.4.0/components/hand-controls.html

Come join to the A-Frame slack to get help with how to make customized tracked-controls https://join.slack.com/t/aframevr/shared_invite/zt-1ybkxuswl-ZcLdiCRUUn2ZtjTr~8c6Eg
